iris.features.required = SSBO CUSTOM_IMAGES

separateAo = true
shadow.culling = reversed
shadow.enabled = true
particles.ordering = before
sky=false
moon=false
sun=false
stars=false
clouds=off

uniform.vec2.resolution = vec2(viewWidth,viewHeight)
uniform.vec2.resolutionInv = vec2(1.0/viewWidth,1.0/viewHeight)


image.voxelcolorimg = voxelcolortex RGBA RGBA8 BYTE true false 256 128 256
image.voxeloccupancyimg = voxeloccupancytex RED_INTEGER R8UI UNSIGNED_BYTE true false 256 128 256