iris.features.required = BLOCK_EMISSION_ATTRIBUTE COMPUTE_SHADERS CUSTOM_IMAGES REVERSED_CULLING SSBO

separateAo = true
shadow.culling = reversed
shadow.enabled = true
particles.ordering = before
sky=false
moon=false
sun=false
stars=false
clouds=off

uniform.vec2.resolution = vec2(viewWidth,viewHeight)
uniform.vec2.resolutionInv = vec2(1.0/viewWidth,1.0/viewHeight)
variable.float.sunDirX = gbufferModelViewInverse.0.0 * sunPosition.x + gbufferModelViewInverse.1.0 * sunPosition.y + gbufferModelViewInverse.2.0 * sunPosition.z
variable.float.sunDirY = gbufferModelViewInverse.0.1 * sunPosition.x + gbufferModelViewInverse.1.1 * sunPosition.y + gbufferModelViewInverse.2.1 * sunPosition.z
variable.float.sunDirZ = gbufferModelViewInverse.0.2 * sunPosition.x + gbufferModelViewInverse.1.2 * sunPosition.y + gbufferModelViewInverse.2.2 * sunPosition.z
variable.float.sunDirNorm = 1.0 / sqrt((sunDirX * sunDirX) + (sunDirY * sunDirY) + (sunDirZ * sunDirZ))
uniform.vec3.sunDir = vec3(sunDirX * sunDirNorm, sunDirY * sunDirNorm, sunDirZ * sunDirNorm)

image.voxelcolorimg = voxelcolortex RGBA RGBA8 BYTE true false 256 128 256
image.voxeloccupancyimg = voxeloccupancytex RED_INTEGER R8UI UNSIGNED_BYTE true false 256 128 256
image.voxeluvimg = voxeluvtex RED_INTEGER R32UI UNSIGNED_INT true false 256 128 256

image.luti_transmittance = luts_transmittance RGBA RGBA16F HALF_FLOAT false false 64 256
image.luti_multiscattering = luts_multiscattering RGBA RGBA16F HALF_FLOAT false false 64 64
image.luti_view = luts_view RGBA RGBA16F HALF_FLOAT false false 256 128


texture.composite.colortex10 = minecraft:textures/atlas/blocks.png
texture.composite.colortex11 = minecraft:textures/atlas/blocks_s.png
